language: python
python:
        - "3.6"
before_install:
        - export MINICONDA=$HOME/miniconda
        - export PATH="MINICONDA/bin:$PATH"
        - hash -r
        - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
        - bash miniconda.sh -b -f -p $MINICONDA
        - conda config --set always_yes yes
        - conda update conda
        - conda info -a
        - echo "Python version var"
        - echo $TRAVIS_PYTHON_VERSION
        - conda env create -n testenv -f environment.yml python=$TRAVIS_PYTHON_VERSION
        - source activate testenv
install:
        - python setup.py install
script:
        - python --version
        - python -m pytest -v --pep8
